# Generated by Django 5.1.5 on 2025-01-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_email_user_unique_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
