# Generated by Django 5.1.5 on 2025-01-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_user_facebook_id_user_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="facebook_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="whatsapp_number",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
