# Generated by Django 5.1.5 on 2025-01-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0004_alter_user_facebook_id_alter_user_whatsapp_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="whatsapp_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="facebook_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
