# Generated by Django 5.1.5 on 2025-01-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="communication",
            name="channel",
        ),
        migrations.AlterField(
            model_name="communication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
