# Generated by Django 5.1.5 on 2025-01-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0002_remove_communication_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communication",
            name="type",
            field=models.CharField(
                choices=[("email", "Email"), ("whatsapp", "WhatsApp")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="communication",
            name="whatsapp_message_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
